project:
  type: website
  output-dir: docs
    

website:
  title: "Home"
  sidebar: false
  search: false
  navbar:
    right:
      
      - icon: arrow-right
        href: about.qmd
        text: About
      
      - icon: graph-up
        href: projects.qmd
        text: Projects
        
      - icon: camera-fill
        href: images.qmd
        text: Photography
        
      - icon: controller
        text: Games
        href: https://alnez.itch.io/
      
      - icon: github
        text: Github
        href: https://github.com/Alnez1953
      
      - icon: youtube
        text: Youtube
        href: https://www.youtube.com/@notalnez8088
        

format:
  html:
    page-layout: full
    theme: cyborg
    css: styles.css
    toc: false

editor: source

